---
title: "Prospective Research Agenda"
author: "Ziqian Xia"
date: "2021-11-19"
categories: [research]
tags: [Academic]
draft: false
---

### Computational Social in Climate Change Perception: A Research Plan

-   Does abnormal weather increase climate change perception and adaptation
    behaviour in Chinese?

#### Method

Scraping and text analysis of social media in abnormal weather situations.

Topic modelling

Sentiment analysis (manual coding and machine‑learning classifiers)

Text similarity

Abnormal weather data (search index; NOAA weather)

#### Key references

1.  **Global climate marches sharply raise attention to climate change:**
    analysis of climate search behaviour in 46 countries.
2.  **Variation of public discourse about the impacts of fracking with
    geographic scale and proximity to proposed development.**

---

### Survey study of CCUS / climate change adaptation or mitigation behaviour

---

### Developing pre‑intervention scales of pro‑environmental behaviour

#### Key problem

$$
F(\text{Personal Predictors}, \text{EnvirPredictor}, ...) = \text{TargetIntervention}
$$

$$
\text{While: Predictors} \rightarrow \text{Intervention} \rightarrow \text{Effect sizes}
$$

That is, using categorical variables to predict a categorical variable by
literature screening.

#### Method

1.  Review key influences and their target behaviour change.
2.  **Set up numerical or categorical relationships between personal
    characteristics and suitable intervention methods.**
3.  Test the effectiveness.
4.  Build a Shiny app or scale wrapper.

---

### Large–scale pre‑registered field intervention in pro‑environmental behaviour

---

### Crowding‑out effect in climate change adaptation behaviour